In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:20pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:20pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:20px;}
</style>
"""))

# 1. tensorflow v2.xx에서 v1 사용하기

In [3]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() #tensorflow v2 비활성화하고 v1만 활성화
import numpy as np
import pandas as pd

Instructions for updating:
non-resource variables are not supported in the long term


## TensorFlow
- 데이터 흐름 그래프(tensor 흐름을 나타내는 설계도)를 사용하는 수치 계산 라이브러리
- 그래프는 node(데이터,연산)와 edge로 구성
- sess = tf.Session()을 이용하여 실행환경
- sess.run()을 통해서 실행결과를 확인

In [6]:
# 1. tensor(상수node, 변수node, 연산node) 정의
node1 = tf.constant('Hello, TensorFlow')
# 2. 세션 생성(실행하는 환경 생성)
sess = tf.Session()
# 3. 실행
print(sess.run(node1))
print(sess.run(node1).decode())

b'Hello, TensorFlow'
Hello, TensorFlow


In [7]:
# 1. 그래프 정의
node1 = tf.constant(10,dtype=tf.float16)
node2= tf.constant(20,dtype=tf.float16)
node3= tf.add(node1,node2)
# 2. 세션 생성
sess = tf.Session()
# 3. 세션 실행 및 결과
n1,n2,n3 = sess.run([node1,node2,node3])
print(n1,n2,n3)


10.0 20.0 30.0


In [8]:
# 타입 변경
node1 = tf.constant(np.array([10,20,30]),dtype=tf.int16)
node2 = tf.cast(node1, dtype=tf.float32)
sess = tf.Session()
print(sess.run([node1,node2]))

[array([10, 20, 30], dtype=int16), array([10., 20., 30.], dtype=float32)]


In [11]:
# 평균값 계산 : tf.reduce_mean()
data = np.array([1.,2,3,4])
m = tf.reduce_mean(data)
sess = tf.Session()
sess.run(m)

2.5

In [13]:
# tf.random_normal([shape]) : 평균0,표준편차는 1인 shape난수 배열. 기본적으로 float32
w = tf.random.normal([1])
sess = tf.Session()
sess.run(w)

array([1.2295438], dtype=float32)

In [17]:
# 변수노드
w = tf.Variable(tf.random.normal([1]) )
sess = tf.Session()
sess.run(tf.global_variables_initializer()) # 난수가 발생될 변수 초기화
sess.run(w)

array([0.3464279], dtype=float32)

# 2. tensorFlow v1을 이용한 회귀분석 구현
## 2.1 독립(입력)변수 x가 1개, 종속(타겟)변수 y가 1개

In [23]:
# tensor 그래프 정의
# 데이터 셋 확보
x = np.array([1,2,3])
y = np.array([2,3,4])
# weight와 bias
w = tf.Variable(tf.random.normal([1]),name='weight')
b = tf.Variable(tf.random.normal([1]),name='bias')
# hat, hypothesis : 결과는 numpy배열
H = w*x+b
# cost function(손실함수:mse) : H-y의 제곱의평균
cost = tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 w와 b를 찾는것
cost함수가 2차함수이므로 곡선 그래프, 곡선위 미분값이 0이 되는 방향학습(경사하강법:GradientDescent)
'''
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
#세션 생성
sess = tf.Session()
# w와 b초기화
sess.run(tf.global_variables_initializer())
# 학습(v2에서의 fit함수)
for step in range(1,6001):
    _,cost_val,w_val, b_val =sess.run([train,cost,w,b])
    if step%300==1:
        print(f'{step}번째 cost:{cost_val},w:{w_val}, b:{b_val}')

1번째 cost:24.61896324157715,w:[-0.5364937], b:[-0.15677485]
301번째 cost:0.005521354731172323,w:[1.0860941], b:[0.8042878]
601번째 cost:0.0013028047978878021,w:[1.0418208], b:[0.90493184]
901번째 cost:0.0003074059495702386,w:[1.0203145], b:[0.9538202]
1201번째 cost:7.253645890159532e-05,w:[1.009868], b:[0.9775677]
1501번째 cost:1.7115848095272668e-05,w:[1.0047935], b:[0.9891033]
1801번째 cost:4.03866897613625e-06,w:[1.0023285], b:[0.99470687]
2101번째 cost:9.535003187011171e-07,w:[1.0011315], b:[0.99742806]
2401번째 cost:2.255606688095213e-07,w:[1.0005505], b:[0.99874926]
2701번째 cost:5.34636050986137e-08,w:[1.000268], b:[0.999391]
3001번째 cost:1.2739409527284806e-08,w:[1.0001307], b:[0.99970263]
3301번째 cost:3.0531879247064353e-09,w:[1.0000643], b:[0.99985456]
3601번째 cost:7.3453421123304e-10,w:[1.0000314], b:[0.9999285]
3901번째 cost:1.86242729571795e-10,w:[1.000016], b:[0.99996406]
4201번째 cost:5.328478283606053e-11,w:[1.0000087], b:[0.9999811]
4501번째 cost:5.328478283606053e-11,w:[1.0000087], b:[0.9999811]

In [24]:
w_,b_ = sess.run([w[0],b[0]])
w_,b_

(1.0000087, 0.9999811)

In [25]:
def predict(x):
    return x*w_ +b_

In [26]:
predict(5)

6.000024616718292

## 2.2 predict을 위한 placeholder이용
- placeholder : 외부에서 데이터를 입력 받을수있는 노드

In [30]:
x = tf.placeholder(dtype=tf.float32)
H = w_*x+b_
sess = tf.Session()
sess.run([H,x],{x:2.5})

[3.5000029, array(2.5, dtype=float32)]

In [31]:
sess.run(H,{x: np.array([2,3,3])})

array([2.9999986, 4.000007 , 4.000007 ], dtype=float32)

In [32]:
# tensor 그래프 정의
# 데이터 셋 확보
x_data = np.array([1,2,3])
y_data = np.array([2,3,4])

# placeholder 노드설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)

# weight와 bias
w = tf.Variable(tf.random.normal([1]),name='weight')
b = tf.Variable(tf.random.normal([1]),name='bias')

# hat, hypothesis : 결과는 numpy배열
H = w*x+b #예측값

# cost function(손실함수:mse) : H-y의 제곱의평균
cost = tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 w와 b를 찾는것
cost함수가 2차함수이므로 곡선 그래프, 곡선위 미분값이 0이 되는 방향학습(경사하강법:GradientDescent)
'''
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
#세션 생성
sess = tf.Session()
# w와 b초기화
sess.run(tf.global_variables_initializer())
# 학습(v2에서의 fit함수)
for step in range(1,6001):
    _,cost_val,w_val, b_val =sess.run([train,cost,w,b],
                                     feed_dict = {x:x_data,y:y_data})
    if step%300==1:
        print(f'{step}번째 cost:{cost_val},w:{w_val}, b:{b_val}')
print(f'{step}번째 cost:{cost_val},w:{w_val}, b:{b_val}')

1번째 cost:0.8455438613891602,w:[0.9412773], b:[0.29549548]
301번째 cost:0.01099798921495676,w:[1.1215088], b:[0.72378224]
601번째 cost:0.0025950863491743803,w:[1.0590237], b:[0.8658252]
901번째 cost:0.0006123311468400061,w:[1.028671], b:[0.93482393]
1201번째 cost:0.00014448576257564127,w:[1.0139271], b:[0.9683403]
1501번째 cost:3.409333658055402e-05,w:[1.0067652], b:[0.9846212]
1801번째 cost:8.044735295698047e-06,w:[1.0032864], b:[0.9925293]
2101번째 cost:1.8984288772116997e-06,w:[1.0015965], b:[0.996371]
2401번째 cost:4.4841672774964536e-07,w:[1.000776], b:[0.99823606]
2701번째 cost:1.0619891099850065e-07,w:[1.0003774], b:[0.9991417]
3001번째 cost:2.5302560047180123e-08,w:[1.000184], b:[0.9995812]
3301번째 cost:6.053369361325167e-09,w:[1.0000899], b:[0.999795]
3601번째 cost:1.4992261876400903e-09,w:[1.0000443], b:[0.999898]
3901번째 cost:3.512970747632238e-10,w:[1.0000217], b:[0.99995077]
4201번째 cost:1.0311396181350574e-10,w:[1.000012], b:[0.9999734]
4501번째 cost:5.195962063386794e-11,w:[1.0000086], b:[0.9999813

In [34]:
# 예측하기
sess.run(H,feed_dict={x:2.5})

array([3.5000029], dtype=float32)

In [35]:
sess.run(H,feed_dict={x:np.array([2.5,3.5])})

array([3.5000029, 4.5000114], dtype=float32)

## 2.3 scale이 다른 데이터들의, 회귀분석 구현(scale조정x)

In [41]:
# tensor 그래프 정의
# 데이터 셋 확보
x_data = np.array([1,2,5,8,10])
y_data = np.array([5,53,64,80,90])

# placeholder 노드설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)

# weight와 bias
w = tf.Variable(tf.random.normal([1]),name='weight')
b = tf.Variable(tf.random.normal([1]),name='bias')

# hat, hypothesis : 결과는 numpy배열
H = w*x+b #예측값

# cost function(손실함수:mse) : H-y의 제곱의평균
cost = tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 w와 b를 찾는것
cost함수가 2차함수이므로 곡선 그래프, 곡선위 미분값이 0이 되는 방향학습(경사하강법:GradientDescent)
'''
# optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
#세션 생성
sess = tf.Session()
# w와 b초기화
sess.run(tf.global_variables_initializer())
# 학습(v2에서의 fit함수)
for step in range(1,6001):
    _,cost_val,w_val, b_val =sess.run([train,cost,w,b],
                                     feed_dict = {x:x_data,y:y_data})
    if step%300==1:
        print(f'{step}번째 cost:{cost_val},w:{w_val}, b:{b_val}')
print(f'{step}번째 cost:{cost_val},w:{w_val}, b:{b_val}')

InvalidArgumentError: Graph execution error:

Detected at node 'Placeholder_8' defined at (most recent call last):
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
      app.launch_new_instance()
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\traitlets\config\application.py", line 1082, in launch_instance
      app.start()
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\ipykernel\kernelapp.py", line 807, in start
      self.io_loop.start()
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\tornado\platform\asyncio.py", line 211, in start
      self.asyncio_loop.run_forever()
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\asyncio\base_events.py", line 603, in run_forever
      self._run_once()
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\asyncio\base_events.py", line 1909, in _run_once
      handle._run()
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\asyncio\events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\ipykernel\utils.py", line 71, in preserve_context
      return await f(*args, **kwargs)
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\ipykernel\kernelbase.py", line 621, in shell_main
      await self.dispatch_shell(msg, subshell_id=subshell_id)
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\ipykernel\kernelbase.py", line 478, in dispatch_shell
      await result
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\ipykernel\ipkernel.py", line 372, in execute_request
      await super().execute_request(stream, ident, parent)
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\ipykernel\kernelbase.py", line 834, in execute_request
      reply_content = await reply_content
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\ipykernel\ipkernel.py", line 460, in do_execute
      res = shell.run_cell(
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\ipykernel\zmqshell.py", line 665, in run_cell
      return super().run_cell(*args, **kwargs)
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
      result = self._run_cell(
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
      result = runner(coro)
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
      coro.send(None)
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\Admin\AppData\Local\Temp\ipykernel_3540\720928811.py", line 7, in <module>
      x = tf.placeholder(dtype=tf.float32)
Node: 'Placeholder_8'
You must feed a value for placeholder tensor 'Placeholder_8' with dtype float
	 [[{{node Placeholder_8}}]]

Original stack trace for 'Placeholder_8':
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\traitlets\config\application.py", line 1082, in launch_instance
    app.start()
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\ipykernel\kernelapp.py", line 807, in start
    self.io_loop.start()
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\tornado\platform\asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\ipykernel\utils.py", line 71, in preserve_context
    return await f(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\ipykernel\kernelbase.py", line 621, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\ipykernel\kernelbase.py", line 478, in dispatch_shell
    await result
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\ipykernel\ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\ipykernel\kernelbase.py", line 834, in execute_request
    reply_content = await reply_content
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\ipykernel\ipkernel.py", line 460, in do_execute
    res = shell.run_cell(
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\ipykernel\zmqshell.py", line 665, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Admin\AppData\Local\Temp\ipykernel_3540\720928811.py", line 7, in <module>
    x = tf.placeholder(dtype=tf.float32)
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\tensorflow\python\ops\array_ops.py", line 3345, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 6897, in placeholder
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 797, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "C:\Users\Admin\anaconda3\envs\ml-dl-nlp\lib\site-packages\tensorflow\python\framework\ops.py", line 3800, in _create_op_internal
    ret = Operation(


## 2.4 scale이 다른 데이터의 회계분석(scare2조정)
### scale 조정방법: 모든데이터를 일정 범위내로 조정-  
- normalization(정규화);모든 데이터를 0~1사이로 조정
                            x-xmin
     normalization =---------------
                           Xmax-Xmin
                * 위의 식보다 라이브러리 추천(sklearn.preprocessinh.MinMaxScaler

- standardization(표준화) : 데이터의 평균을 0,표준편차를 1로 지정
                                
    ststandardization= ---------------
    
    

In [44]:
#라이브러리를 쓰지 않고 정규화
x_data = np.array([1,2,5,8,10])
y_data = np.array([5,15,68,80,95])
norm_scale_x_data = (x_data - x_data.min()) / (x_data.max() - x_data.min())
norm_scale_y_data = (y_data - y_data.min()) / (y_data.max() - y_data.min())
print(norm_scale_x_data)
print(norm_scale_y_data)

[0.         0.11111111 0.44444444 0.77777778 1.        ]
[0.         0.11111111 0.7        0.83333333 1.        ]


In [48]:
# 라이브러리를 사용하여 정규화
from sklearn.preprocessing import MinMaxScaler, StandardScaler
x_data = np.array([1,2,5,8,10])ㅍㅍ
y_data = np.array([5,15,68,80,95]).reshape(-1,1)
scaler_x = MinMaxScaler() # x_data를 변환시킬객체
scaler_x.fit(x_data)
norm_scaled_x_data = scaler_x.transform(x_data)
scaler_y = MinMaxScaler() # y_data를 변환시킬객체
# scaler_y.fit(y_data)
# norm_scale_y_data = scaler_y.transform(y_data)
norm_scaled_y_data = scaler_y.fit_transform(y_data)

# print(norm_scale_x_data)
# print(norm_scale_y_data)
np.column_stack([x_data, norm_scaled_x_data, y_data, norm_scaled_y_data])

array([[ 1.        ,  0.        ,  5.        ,  0.        ],
       [ 2.        ,  0.11111111, 15.        ,  0.11111111],
       [ 5.        ,  0.44444444, 68.        ,  0.7       ],
       [ 8.        ,  0.77777778, 80.        ,  0.83333333],
       [10.        ,  1.        , 95.        ,  1.        ]])

In [49]:
# 라이브러리를 쓰지않고 표준화
x_data = np.array([1,2,5,8,10])
y_data = np.array([5,15,68,80,95])
stan_scaled_x_data = (x_data - x_data.mean()) / x_data.std()
stan_scaled_y_data = (y_data - y_data.mean()) / y_data.std()
print(np.column_stack([x_data, norm_scaled_x_data, x_data, norm_scaled_x_data]))
print()
print(np.column_stack([y_data, norm_scaled_y_data, y_data, norm_scaled_y_data]))

[[ 1.          0.          1.          0.        ]
 [ 2.          0.11111111  2.          0.11111111]
 [ 5.          0.44444444  5.          0.44444444]
 [ 8.          0.77777778  8.          0.77777778]
 [10.          1.         10.          1.        ]]

[[ 5.          0.          5.          0.        ]
 [15.          0.11111111 15.          0.11111111]
 [68.          0.7        68.          0.7       ]
 [80.          0.83333333 80.          0.83333333]
 [95.          1.         95.          1.        ]]


In [50]:
# 라이브러리를 사용하여 표준화
x_data = np.array([1,2,5,8,10]).reshape(-1,1)
y_data = np.array([5,15,68,80,95]).reshape(-1,1)
scaler_x = StandardScaler()
stan_scaled_x_data = scaler_x.fit_transform(x_data)
scaler_y = StandardScaler()
stan_scaled_y_data = scaler_y.fit_transform(y_data)
np.column_stack([stan_scaled_x_data,stan_scaled_y_data])

array([[-1.22474487, -1.32373476],
       [-0.93313895, -1.04563922],
       [-0.05832118,  0.42826713],
       [ 0.81649658,  0.76198177],
       [ 1.39970842,  1.17912508]])

In [51]:
# 스케일 조정된 데이터를 다시 복구 : inverse_transform()이용
scaler_x.inverse_transform(stan_scaled_x_data)

array([[ 1.],
       [ 2.],
       [ 5.],
       [ 8.],
       [10.]])

In [52]:
scaler_y.inverse_transform(stan_scaled_y_data)

array([[ 5.],
       [15.],
       [68.],
       [80.],
       [95.]])

In [55]:
# tensor 그래프 정의
# 데이터 셋 확보
x_data = np.array([1,2,5,8,10])
y_data = np.array([5,53,64,80,90])

# placeholder 노드설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)

# weight와 bias
w = tf.Variable(tf.random.normal([1]),name='weight')
b = tf.Variable(tf.random.normal([1]),name='bias')

# hat, hypothesis : 결과는 numpy배열
H = w*x+b #예측값

# cost function(손실함수:mse) : H-y의 제곱의평균
cost = tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 w와 b를 찾는것
cost함수가 2차함수이므로 곡선 그래프, 곡선위 미분값이 0이 되는 방향학습(경사하강법:GradientDescent)
'''
# optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
#세션 생성
sess = tf.Session()
# w와 b초기화
sess.run(tf.global_variables_initializer())
# 학습(v2에서의 fit함수)
for step in range(1,2001):
    _,cost_val =sess.run([train,cost],
                                     feed_dict = {x:norm_scale_x_data,
                                                  y:norm_scale_y_data})
    if step%300==1:
        print(f'{step}번째 cost:{cost_val}')
print(f'{step}번째 cost:{cost_val}')

1번째 cost:1.8954859972000122
301번째 cost:0.16335274279117584
601번째 cost:0.16055195033550262
901번째 cost:0.15986093878746033
1201번째 cost:0.15969042479991913
1501번째 cost:0.1596483588218689
1801번째 cost:0.15963797271251678
2000번째 cost:0.15963590145111084


## 2.5 독립변수 x가 3개 타겟변수 y가 1개인 회귀분석