In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:20pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:20pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:20px;}
</style>
"""))

# 1. tensorflow v2.xx에서 v1 사용하기

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() #tensorflow v2 비활성화하고 v1만 활성화
import numpy as np
import pandas as pd

Instructions for updating:
non-resource variables are not supported in the long term


## TensorFlow
- 데이터 흐름 그래프(tensor 흐름을 나타내는 설계도)를 사용하는 수치 계산 라이브러리
- 그래프는 node(데이터,연산)와 edge로 구성
- sess = tf.Session()을 이용하여 실행환경
- sess.run()을 통해서 실행결과를 확인

In [3]:
# 1. tensor(상수node, 변수node, 연산node) 정의
node1 = tf.constant('Hello, TensorFlow')
# 2. 세션 생성(실행하는 환경 생성)
sess = tf.Session()
# 3. 실행
print(sess.run(node1))
print(sess.run(node1).decode())

b'Hello, TensorFlow'
Hello, TensorFlow


In [4]:
# 1. 그래프 정의
node1 = tf.constant(10,dtype=tf.float16)
node2= tf.constant(20,dtype=tf.float16)
node3= tf.add(node1,node2)
# 2. 세션 생성
sess = tf.Session()
# 3. 세션 실행 및 결과
n1,n2,n3 = sess.run([node1,node2,node3])
print(n1,n2,n3)


10.0 20.0 30.0


In [5]:
# 타입 변경
node1 = tf.constant(np.array([10,20,30]),dtype=tf.int16)
node2 = tf.cast(node1, dtype=tf.float32)
sess = tf.Session()
print(sess.run([node1,node2]))

[array([10, 20, 30], dtype=int16), array([10., 20., 30.], dtype=float32)]


In [6]:
# 평균값 계산 : tf.reduce_mean()
data = np.array([1.,2,3,4])
m = tf.reduce_mean(data)
sess = tf.Session()
sess.run(m)

2.5

In [7]:
# tf.random_normal([shape]) : 평균0,표준편차는 1인 shape난수 배열. 기본적으로 float32
w = tf.random.normal([1])
sess = tf.Session()
sess.run(w)

array([-0.3766555], dtype=float32)

In [8]:
# 변수노드
w = tf.Variable(tf.random.normal([1]) )
sess = tf.Session()
sess.run(tf.global_variables_initializer()) # 난수가 발생될 변수 초기화
sess.run(w)

array([0.7130604], dtype=float32)

# 2. tensorFlow v1을 이용한 회귀분석 구현
## 2.1 독립(입력)변수 x가 1개, 종속(타겟)변수 y가 1개

In [9]:
# tensor 그래프 정의
# 데이터 셋 확보
x = np.array([1,2,3])
y = np.array([2,3,4])
# weight와 bias
w = tf.Variable(tf.random.normal([1]),name='weight')
b = tf.Variable(tf.random.normal([1]),name='bias')
# hat, hypothesis : 결과는 numpy배열
H = w*x+b
# cost function(손실함수:mse) : H-y의 제곱의평균
cost = tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 w와 b를 찾는것
cost함수가 2차함수이므로 곡선 그래프, 곡선위 미분값이 0이 되는 방향학습(경사하강법:GradientDescent)
'''
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
#세션 생성
sess = tf.Session()
# w와 b초기화
sess.run(tf.global_variables_initializer())
# 학습(v2에서의 fit함수)
for step in range(1,6001):
    _,cost_val,w_val, b_val =sess.run([train,cost,w,b])
    if step%300==1:
        print(f'{step}번째 cost:{cost_val},w:{w_val}, b:{b_val}')

1번째 cost:44.02155685424805,w:[-0.91633594], b:[-0.8567702]
301번째 cost:0.024539852514863014,w:[1.1815041], b:[0.5873983]
601번째 cost:0.005790397524833679,w:[1.0881668], b:[0.79957616]
901번째 cost:0.0013663051649928093,w:[1.0428277], b:[0.90264255]
1201번째 cost:0.00032238976564258337,w:[1.0208038], b:[0.9527081]
1501번째 cost:7.607004226883873e-05,w:[1.0101056], b:[0.9770279]
1801번째 cost:1.795001662685536e-05,w:[1.0049089], b:[0.98884094]
2101번째 cost:4.235660981066758e-06,w:[1.0023847], b:[0.9945793]
2401번째 cost:1.0002063390857074e-06,w:[1.0011588], b:[0.99736583]
2701번째 cost:2.365285922678595e-07,w:[1.0005636], b:[0.998719]
3001번째 cost:5.607377673300107e-08,w:[1.0002744], b:[0.9993762]
3301번째 cost:1.3368201656760448e-08,w:[1.0001338], b:[0.9996955]
3601번째 cost:3.2081384215842945e-09,w:[1.0000657], b:[0.999851]
3901번째 cost:7.738130136658583e-10,w:[1.0000321], b:[0.9999267]
4201번째 cost:1.926376141936359e-10,w:[1.0000162], b:[0.99996346]
4501번째 cost:5.328478283606053e-11,w:[1.0000087], b:[0.999

In [14]:
w_,b_ = sess.run([w[0],b[0]])
w_,b_

(1.0000087, 0.9999811)

In [12]:
def predict(x):
    return x*w_ +b_

In [15]:
predict(5)

6.000024616718292

## 2.2 predict을 위한 placeholder이용
- placeholder : 외부에서 데이터를 입력 받을수있는 노드

In [16]:
x = tf.placeholder(dtype=tf.float32)
H = w_*x+b_
sess = tf.Session()
sess.run([H,x],{x:2.5})

[3.5000029, array(2.5, dtype=float32)]

In [17]:
sess.run(H,{x: np.array([2,3,3])})

array([2.9999986, 4.000007 , 4.000007 ], dtype=float32)

In [18]:
# tensor 그래프 정의
# 데이터 셋 확보
x_data = np.array([1,2,3])
y_data = np.array([2,3,4])

# placeholder 노드설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)

# weight와 bias
w = tf.Variable(tf.random.normal([1]),name='weight')
b = tf.Variable(tf.random.normal([1]),name='bias')

# hat, hypothesis : 결과는 numpy배열
H = w*x+b #예측값

# cost function(손실함수:mse) : H-y의 제곱의평균
cost = tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 w와 b를 찾는것
cost함수가 2차함수이므로 곡선 그래프, 곡선위 미분값이 0이 되는 방향학습(경사하강법:GradientDescent)
'''
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
#세션 생성
sess = tf.Session()
# w와 b초기화
sess.run(tf.global_variables_initializer())
# 학습(v2에서의 fit함수)
for step in range(1,6001):
    _,cost_val,w_val, b_val =sess.run([train,cost,w,b],
                                     feed_dict = {x:x_data,y:y_data})
    if step%300==1:
        print(f'{step}번째 cost:{cost_val},w:{w_val}, b:{b_val}')
print(f'{step}번째 cost:{cost_val},w:{w_val}, b:{b_val}')

1번째 cost:84.63153076171875,w:[-1.7632906], b:[-1.3367656]
301번째 cost:0.030015796422958374,w:[1.200736], b:[0.54367954]
601번째 cost:0.0070825121365487576,w:[1.0975088], b:[0.7783395]
901번째 cost:0.0016711828066036105,w:[1.0473654], b:[0.89232713]
1201번째 cost:0.00039432395715266466,w:[1.0230081], b:[0.94769746]
1501번째 cost:9.304715058533475e-05,w:[1.0111763], b:[0.9745936]
1801번째 cost:2.1956459022476338e-05,w:[1.005429], b:[0.9876585]
2101번째 cost:5.180634616408497e-06,w:[1.0026373], b:[0.99400496]
2401번째 cost:1.2232230801600963e-06,w:[1.0012816], b:[0.99708706]
2701번째 cost:2.8900112170049397e-07,w:[1.0006229], b:[0.9985838]
3001번째 cost:6.851947631503208e-08,w:[1.0003037], b:[0.9993106]
3301번째 cost:1.635828539292561e-08,w:[1.0001485], b:[0.99966323]
3601번째 cost:3.899022882336567e-09,w:[1.0000724], b:[0.9998356]
3901번째 cost:9.364811148770968e-10,w:[1.0000353], b:[0.9999193]
4201번째 cost:2.224661982408449e-10,w:[1.0000173], b:[0.99996096]
4501번째 cost:6.518519057863159e-11,w:[1.0000097], b:[0.9

In [19]:
# 예측하기
sess.run(H,feed_dict={x:2.5})

array([3.5000029], dtype=float32)

In [20]:
sess.run(H,feed_dict={x:np.array([2.5,3.5])})

array([3.5000029, 4.5000114], dtype=float32)

## 2.3 scale이 다른 데이터들의, 회귀분석 구현(scale조정x)

In [21]:
# tensor 그래프 정의
# 데이터 셋 확보
x_data = np.array([1,2,5,8,10])
y_data = np.array([5,53,64,80,90])

# placeholder 노드설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)

# weight와 bias
w = tf.Variable(tf.random.normal([1]),name='weight')
b = tf.Variable(tf.random.normal([1]),name='bias')

# hat, hypothesis : 결과는 numpy배열
H = w*x+b #예측값

# cost function(손실함수:mse) : H-y의 제곱의평균
cost = tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 w와 b를 찾는것
cost함수가 2차함수이므로 곡선 그래프, 곡선위 미분값이 0이 되는 방향학습(경사하강법:GradientDescent)
'''
# optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
#세션 생성
sess = tf.Session()
# w와 b초기화
sess.run(tf.global_variables_initializer())
# 학습(v2에서의 fit함수)
for step in range(1,6001):
    _,cost_val,w_val, b_val =sess.run([train,cost,w,b],
                                     feed_dict = {x:x_data,y:y_data})
    if step%300==1:
        print(f'{step}번째 cost:{cost_val},w:{w_val}, b:{b_val}')
print(f'{step}번째 cost:{cost_val},w:{w_val}, b:{b_val}')

1번째 cost:3171.118408203125,w:[8.115563], b:[1.8115842]
301번째 cost:180.95321655273438,w:[8.064735], b:[15.653397]
601번째 cost:178.74542236328125,w:[7.758534], b:[17.9206]
901번째 cost:178.68405151367188,w:[7.7074895], b:[18.298548]
1201번째 cost:178.68235778808594,w:[7.698981], b:[18.361551]
1501번째 cost:178.6823272705078,w:[7.6975627], b:[18.37205]
1801번째 cost:178.68231201171875,w:[7.697329], b:[18.37378]
2101번째 cost:178.68231201171875,w:[7.6973], b:[18.373993]
2401번째 cost:178.68231201171875,w:[7.6973], b:[18.373993]
2701번째 cost:178.68231201171875,w:[7.6973], b:[18.373993]
3001번째 cost:178.68231201171875,w:[7.6973], b:[18.373993]
3301번째 cost:178.68231201171875,w:[7.6973], b:[18.373993]
3601번째 cost:178.68231201171875,w:[7.6973], b:[18.373993]
3901번째 cost:178.68231201171875,w:[7.6973], b:[18.373993]
4201번째 cost:178.68231201171875,w:[7.6973], b:[18.373993]
4501번째 cost:178.68231201171875,w:[7.6973], b:[18.373993]
4801번째 cost:178.68231201171875,w:[7.6973], b:[18.373993]
5101번째 cost:178.68231201171

## 2.4 scale이 다른 데이터의 회계분석(scare2조정)
### scale 조정방법: 모든데이터를 일정 범위내로 조정-  
- normalization(정규화);모든 데이터를 0~1사이로 조정
                                       x-xmin
            normalization = ────────────────────────── 
                                      Xmax-Xmin
                * 위의 식보다 라이브러리 추천(sklearn.preprocessinh.MinMaxScaler)

- standardization(표준화) : 데이터의 평균을 0,표준편차를 1로 지정
                                
                                X-Xmean standardization
         ststandardization= ──────────────────────────     
                                       Xstd(표준편차) 
               * 위의 식보다 라이브러리 추천(sklearn.preprocessing.StandardScaler)                   

In [25]:
#라이브러리를 쓰지 않고 정규화
x_data = np.array([1,2,5,8,10])
y_data = np.array([5,15,68,80,95])
norm_scale_x_data = (x_data - x_data.min()) / (x_data.max() - x_data.min())
norm_scale_y_data = (y_data - y_data.min()) / (y_data.max() - y_data.min())
print(norm_scale_x_data)
print(norm_scale_y_data)

[0.         0.11111111 0.44444444 0.77777778 1.        ]
[0.         0.11111111 0.7        0.83333333 1.        ]


In [28]:
# 라이브러리를 사용하여 정규화
from sklearn.preprocessing import MinMaxScaler, StandardScaler
x_data = np.array([1,2,5,8,10]).reshape(-1, 1)
y_data = np.array([5,15,68,80,95]).reshape(-1,1)
scaler_x = MinMaxScaler() # x_data를 변환시킬객체
scaler_x.fit(x_data)
norm_scaled_x_data = scaler_x.transform(x_data)
scaler_y = MinMaxScaler() # y_data를 변환시킬객체
# scaler_y.fit(y_data)
# norm_scale_y_data = scaler_y.transform(y_data)
norm_scaled_y_data = scaler_y.fit_transform(y_data)

# print(norm_scale_x_data)
# print(norm_scale_y_data)
np.column_stack([x_data, norm_scaled_x_data, y_data, norm_scaled_y_data])

array([[ 1.        ,  0.        ,  5.        ,  0.        ],
       [ 2.        ,  0.11111111, 15.        ,  0.11111111],
       [ 5.        ,  0.44444444, 68.        ,  0.7       ],
       [ 8.        ,  0.77777778, 80.        ,  0.83333333],
       [10.        ,  1.        , 95.        ,  1.        ]])

In [29]:
# 라이브러리를 쓰지않고 표준화
x_data = np.array([1,2,5,8,10])
y_data = np.array([5,15,68,80,95])
stan_scaled_x_data = (x_data - x_data.mean()) / x_data.std()
stan_scaled_y_data = (y_data - y_data.mean()) / y_data.std()
print(np.column_stack([x_data, norm_scaled_x_data, x_data, norm_scaled_x_data]))
print()
print(np.column_stack([y_data, norm_scaled_y_data, y_data, norm_scaled_y_data]))

[[ 1.          0.          1.          0.        ]
 [ 2.          0.11111111  2.          0.11111111]
 [ 5.          0.44444444  5.          0.44444444]
 [ 8.          0.77777778  8.          0.77777778]
 [10.          1.         10.          1.        ]]

[[ 5.          0.          5.          0.        ]
 [15.          0.11111111 15.          0.11111111]
 [68.          0.7        68.          0.7       ]
 [80.          0.83333333 80.          0.83333333]
 [95.          1.         95.          1.        ]]


In [30]:
# 라이브러리를 사용하여 표준화
x_data = np.array([1,2,5,8,10]).reshape(-1,1)
y_data = np.array([5,15,68,80,95]).reshape(-1,1)
scaler_x = StandardScaler()
stan_scaled_x_data = scaler_x.fit_transform(x_data)
scaler_y = StandardScaler()
stan_scaled_y_data = scaler_y.fit_transform(y_data)
np.column_stack([stan_scaled_x_data,stan_scaled_y_data])

array([[-1.22474487, -1.32373476],
       [-0.93313895, -1.04563922],
       [-0.05832118,  0.42826713],
       [ 0.81649658,  0.76198177],
       [ 1.39970842,  1.17912508]])

In [31]:
# 스케일 조정된 데이터를 다시 복구 : inverse_transform()이용
scaler_x.inverse_transform(stan_scaled_x_data)

array([[ 1.],
       [ 2.],
       [ 5.],
       [ 8.],
       [10.]])

In [32]:
scaler_y.inverse_transform(stan_scaled_y_data)

array([[ 5.],
       [15.],
       [68.],
       [80.],
       [95.]])

In [33]:
# tensor 그래프 정의
# 데이터 셋 확보
x_data = np.array([1,2,5,8,10])
y_data = np.array([5,53,64,80,90])

# placeholder 노드설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)

# weight와 bias
w = tf.Variable(tf.random.normal([1]),name='weight')
b = tf.Variable(tf.random.normal([1]),name='bias')

# hat, hypothesis : 결과는 numpy배열
H = w*x+b #예측값

# cost function(손실함수:mse) : H-y의 제곱의평균
cost = tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 w와 b를 찾는것
cost함수가 2차함수이므로 곡선 그래프, 곡선위 미분값이 0이 되는 방향학습(경사하강법:GradientDescent)
'''
# optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)
# optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
# train = optimizer.minimize(cost)
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)
#세션 생성
sess = tf.Session()
# w와 b초기화
sess.run(tf.global_variables_initializer())
# 학습(v2에서의 fit함수)
for step in range(1,2001):
    _, cost_val =sess.run([train,cost],
                      feed_dict = {x:norm_scaled_x_data,
                                   y:norm_scaled_y_data})
    if step%300==1:
        print(f'{step}번째 cost:{cost_val}')
print(f'{step}번째 cost:{cost_val}')

1번째 cost:0.318187415599823
301번째 cost:0.010863007046282291
601번째 cost:0.010039922781288624
901번째 cost:0.009836834855377674
1201번째 cost:0.009786720387637615
1501번째 cost:0.009774351492524147
1801번째 cost:0.009771304205060005
2000번째 cost:0.009770696982741356


## 2.5 독립변수 x가 3개 타겟변수 y가 1개인 회귀분석
- 교안 25P

In [13]:
# data set
X_data = np.array([[73,80,75], # 학습시에는 x에 5행3열 / 예측시 ?행 3열
                 [93,88,93],
                 [89,91,90],
                 [96,98,100],
                 [73,66,70]])
y_data = np.array([[152],    # 학습시에는 y에 5행1열 / 예측시에는 ?행 1열
                  [185],
                  [180],
                  [196],
                  [142]])
X = tf.placeholder(shape=[None,3],dtype=tf.float32)
y = tf.placeholder(shape=[None,1],dtype=tf.float32)
# w & b
W = tf.Variable(tf.random.normal([3,1]))
b = tf.Variable(tf.random.normal([1]))
#예측값
H = X @ W + b # @행렬곱
H = tf.matmul(X,W) + b
#손실함수(loss) : mse
cost = tf.reduce_mean(tf.square(H - y))
# optimizer & train
train = tf.train.GradientDescentOptimizer(learning_rate=0.00004).minimize(cost)
# sess 생성 & variable 초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())
# 학습
for step in range(1,20001):
    _,cost_val = sess.run([train,cost], feed_dict={X:X_data,
                                                   y:y_data})
    if step%1000==1:
        print(f'{step}번째 cost : {cost_val}')
print(f'최종{step}번째 cost : {cost_val}')

1번째 cost : 11528.044921875
1001번째 cost : 8.529253005981445
2001번째 cost : 3.029768228530884
3001번째 cost : 2.0622000694274902
4001번째 cost : 1.6724879741668701
5001번째 cost : 1.3980660438537598
6001번째 cost : 1.1773563623428345
7001번째 cost : 0.9961959719657898
8001번째 cost : 0.8470656275749207
9001번째 cost : 0.7242575883865356
10001번째 cost : 0.6230976581573486
11001번째 cost : 0.5397793054580688
12001번째 cost : 0.47116222977638245
13001번째 cost : 0.4146490693092346
14001번째 cost : 0.3681007921695709
15001번째 cost : 0.3297542631626129
16001번째 cost : 0.2981746196746826
17001번째 cost : 0.27216580510139465
18001번째 cost : 0.2507379949092865
19001번째 cost : 0.23308205604553223
최종20000번째 cost : 0.21854686737060547


In [14]:
# 예측
input_data = np.array([[72,79,74],
                      [92,87,92]])
sess.run(H, feed_dict={X:input_data})

array([[149.32141],
       [182.71368]], dtype=float32)

In [15]:
sess.run(H, feed_dict={X:input_data})

array([[149.32141],
       [182.71368]], dtype=float32)

## scale조정 후 학습하고 예측하기 

In [16]:
from sklearn.preprocessing import StandardScaler
X_data = np.array([[73,80,75], # 학습시에는 x에 5행3열 / 예측시 ?행 3열
                 [93,88,93],
                 [89,91,90],
                 [96,98,100],
                 [73,66,70]])
y_data = np.array([[152],    # 학습시에는 y에 5행1열 / 예측시에는 ?행 1열
                  [185],
                  [180],
                  [196],
                  [142]])
scaler_x = StandardScaler()
scaler_y = StandardScaler()
scaled_x_data = scaler_x.fit_transform(X_data)
scaled_y_data = scaler_y.fit_transform(y_data)
np.column_stack([scaled_x_data,scaled_y_data])

array([[-1.19344226, -0.42020085, -0.93897274, -0.92622337],
       [ 0.82934123,  0.31058324,  0.65550927,  0.68248038],
       [ 0.42478453,  0.58462728,  0.38976227,  0.43873739],
       [ 1.13275875,  1.22406336,  1.27558561,  1.21871496],
       [-1.19344226, -1.69907302, -1.38188441, -1.41370936]])

In [17]:
X = tf.placeholder(shape=[None,3],dtype=tf.float32)
y = tf.placeholder(shape=[None,1],dtype=tf.float32)
# w & b
W = tf.Variable(tf.random.normal([3,1]))
b = tf.Variable(tf.random.normal([1]))
#예측값
# H = X @ W + b # @,tf.matmul()행렬곱
H = tf.matmul(X,W) + b
#손실함수(loss) : mse
cost = tf.reduce_mean(tf.square(H - y))
# optimizer & train
train = tf.train.GradientDescentOptimizer(learning_rate=0.00004).minimize(cost)
# sess 생성 & variable 초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())
# 학습
for step in range(1,20001):
    _,cost_val = sess.run([train,cost], feed_dict={X:scaled_x_data,
                                                   y:scaled_y_data})
    if step%1000==1:
        print(f'{step}번째 cost : {cost_val}')
print(f'최종{step}번째 cost : {cost_val}')

1번째 cost : 1.0951082706451416
1001번째 cost : 0.8618442416191101
2001번째 cost : 0.6897574663162231
3001번째 cost : 0.5599477291107178
4001번째 cost : 0.4599461555480957
5001번째 cost : 0.38142237067222595
6001번째 cost : 0.3187258839607239
7001번째 cost : 0.2679549753665924
8001번째 cost : 0.22636084258556366
9001번째 cost : 0.1919655203819275
10001번째 cost : 0.16331259906291962
11001번째 cost : 0.1393057107925415
12001번째 cost : 0.11910201609134674
13001번째 cost : 0.1020408421754837
14001번째 cost : 0.08759565651416779
15001번째 cost : 0.07534081488847733
16001번째 cost : 0.06492774933576584
17001번째 cost : 0.05606876686215401
18001번째 cost : 0.04852456972002983
19001번째 cost : 0.04209468513727188
최종20000번째 cost : 0.03661574795842171


In [20]:
#예측
input_data = np.array([[72,79,74],
                      [92,87,92]])
scaled_input_data = scaler_x.transform(input_data)
print('scale조정된 입력값 : \n',scaled_input_data)
hat = sess.run(H, feed_dict={X:scaled_input_data})
predict_data = scaler_y.inverse_transform(hat)
print('예측점수:\n',predict_data)

scale조정된 입력값 : 
 [[-1.29458143 -0.51154887 -1.02755507]
 [ 0.72820205  0.21923523  0.56692694]]
예측점수:
 [[151.01819]
 [187.56633]]


In [21]:
input_data = [[90,85,90]]
hat = sess.run(H,feed_dict={X:scaler_x.transform(input_data)})
scaler_y.inverse_transform(hat)

array([[183.40642]], dtype=float32)